[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[language-server.pyright.config]
typeCheckingMode = "basic"
reportMissingImports = "error"

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.vtsls.config.vtsls]
autoUseWorkspaceTsdk = true

[language-server.vtsls.config.vtsls.experimental.completion]
enableServerSideFuzzyMatch = true

[language-server.vtsls.config.vtsls.tsserver]
globalPlugins = [
  { name = "@vue/typescript-plugin", location = "/home/andrew/.local/share/mise/installs/node/25.2.1/lib/node_modules/@vue/language-server/node_modules/@vue/typescript-plugin", languages = ["vue"] }
]

[language-server.vtsls.config.typescript.inlayHints]
parameterNames = { enabled = "all" }
parameterTypes = { enabled = true }
variableTypes = { enabled = true }
propertyDeclarationTypes = { enabled = true }
functionLikeReturnTypes = { enabled = true }

[[language]]
name = "vue"
language-servers = ["vtsls"]
formatter = { command = "prettier", args = ["--parser", "vue"] }
auto-format = true

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server", "emmet-ls"]

# https://github.com/olrtg/emmet-language-server?tab=readme-ov-file#helix
[[language]]
name = "html"
roots = [".git"]
formatter = { command = "prettier", args = ["--parser", "html"] }
language-servers = ["vscode-html-language-server", "emmet-ls"]

[[language]]
name = "php"
language-servers = [ "intelephense","tailwindcss-ls","vscode-html-language-server" ]
auto-format = true

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", ".git"]
language-servers = ["basedpyright", "ruff"]
formatter = { command = "ruff", args = ["format", "-"]}
auto-format = true
